services:
  backend:
    build: .
    container_name: toBeExpertBackend
    command: >
      sh -c "python manage.py makemigrations accounts home order payment resume templates_app &&
            python manage.py migrate &&
            python manage.py createsuperuser_if_not_exists &&
            python manage.py collectstatic --noinput &&
            python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/backend
      - ./static:/app/static
    ports:
      - "8001:8001"
    restart: on-failure

  celery:
    container_name: toBeExpertCelery
    build: .
    command: celery -A backend worker --loglevel=info
    volumes:
      - .:/code
    restart: on-failure
  
volumes:
  backend: